# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Jeanna Diedrich
tagline:          'my blog'
description:      'A place to see progress'
url:              jeannadiedrich.com
baseurl:          /

author:
  name:           'Jeanna J Diedrich'
  url:            https://twitter.com/jeannajdee

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jeannadiedrich/jeanna_blog

gems: [jekyll-paginate, jekyll-gist]

# cd 
# ls
# git status
# git add .
# git status
# git commit -m "note here"
# git push
